### ISSUE TITLE
every items added in the 'Settings' menu if user clicks that button before the 'More'

### ISSUE THREAD

**Issue by htsign** [sienori/G-Search-Plus#2]
**ja**
![search_example_ja](https://user-images.githubusercontent.com/1135891/45393806-9c4dd280-b668-11e8-8b28-e57a144d8c8c.png)
**en**
![search_example_en](https://user-images.githubusercontent.com/1135891/45393807-9c4dd280-b668-11e8-9a30-cf42b6df84f4.png)

**Comment by sienori** [comment]
I merged the pull request.
Thanks!!

P.S. Sorry for my late reply.
